version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8764:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: ltkZPbxzP3m8HA6c
      MYSQL_DATABASE: IA_Pau_database
